export const defaultSettings = {
  pgName: 'Sree Kunj Girls PG',
  tagline: 'Safe, Serene & Luxurious Accommodation for Women',
  description:
    'Sree Kunj Girls PG offers premium student living tailored for scholars and young professionals attending JECRC University, Poornima University, and surrounding institutions in Jaipur. Designed with 24/7 security, high-speed Wi-Fi, chef-prepared hygienic meals, and pristine air-conditioned living spaces across 4 dedicated floors.',
  whatsappNumber: '918957356189',
  contactPhone: '+91 98765 43210',
  contactEmail: 'admissions@sreekunjgirlspg.com',
  address: 'Plot 42, Institutional Corridor, Near JECRC University Gate, Sitapura Industrial Area, Jaipur, Rajasthan 302022',
  city: 'Jaipur',
  state: 'Rajasthan',
  pincode: '302022',
  nearbyColleges: [
    { name: 'JECRC University', distance: '450 meters', travelTime: '2 mins walking' },
    { name: 'Poornima University', distance: '1.2 km', travelTime: '4 mins drive' },
    { name: 'Mahatma Gandhi Medical College', distance: '2.5 km', travelTime: '7 mins drive' },
    { name: 'Sitapura RIICO Tech Zone', distance: '1.8 km', travelTime: '5 mins drive' },
  ],
  googleMapsEmbedUrl:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3561.427771746247!2d75.8761168!3d26.7945037!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x396dc9bd0b3eb2b3%3A0x7d6fcf4a572c65a4!2sJECRC%20University!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin',
  googleMapsDirectionsUrl: 'https://maps.google.com/?q=JECRC+University+Jaipur',
  heroVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-modern-apartment-living-room-with-a-view-41484-large.mp4',
  heroPosterUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1920&q=80',
  heroHeading: 'Sree Kunj Girls PG',
  heroSubheading:
    'Discover an oasis of peace, safety, and elegance near JECRC & Poornima University. Fully furnished 4-floor residences with high-speed fiber, biometric entry, and organic dining.',
  heroBadge: 'Girls PG in Jaipur • Near JECRC & Poornima',
  seoTitle: 'Sree Kunj Girls PG Jaipur | Luxury Girls Accommodation Near JECRC & Poornima University',
  seoDescription:
    'Experience Jaipur’s most premium Girls PG near JECRC and Poornima University. 4 floors of AC/Non-AC rooms, 24/7 security, high-speed Wi-Fi, chef meals & video tour booking.',
  seoKeywords: [
    'Girls PG near JECRC',
    'Girls PG near JECRC University',
    'Girls PG near Poornima University',
    'Girls PG Jaipur',
    'Girls hostel near JECRC',
    'PG near JECRC Jaipur',
    'PG near Poornima University',
    'Female PG near JECRC',
    'Student accommodation near JECRC',
    'Girls accommodation near Poornima',
    'Girls PG near me in Jaipur',
  ],
};

export const defaultRooms = [
  // FLOOR 1
  {
    roomNumber: '101',
    floor: 1,
    type: 'Deluxe Private Studio AC',
    isAc: true,
    price: 13500,
    capacity: 1,
    description: 'Spacious private executive room with plush single bed, study desk, attached balcony, and ambient lighting.',
    facilities: ['Split AC', 'Attached Washroom', 'Private Balcony', 'High-Speed Wi-Fi', 'Wardrobe with Digital Locker', 'Daily Housekeeping'],
    images: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1582582621959-48d27397dc69?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: true,
  },
  {
    roomNumber: '102',
    floor: 1,
    type: 'Luxury Twin Sharing AC',
    isAc: true,
    price: 9500,
    capacity: 2,
    description: 'Comfortable 2-seater room with ergonomic study setups, orthopedic mattresses, and natural sunlit windows.',
    facilities: ['Split AC', 'Ensuite Bathroom', 'Dual Study Stations', 'Dedicated Wardrobes', 'High-Speed Wi-Fi', 'Hot Water Geyser'],
    images: [
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1540518614846-7ede433c4ef2?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: false,
  },
  {
    roomNumber: '103',
    floor: 1,
    type: 'Triple Sharing Comfort (Non-AC)',
    isAc: false,
    price: 7500,
    capacity: 3,
    description: 'Economical yet high-quality triple sharing room with individual study desks and large ventilating windows.',
    facilities: ['Ceiling Fans + Desert Cooler', 'Attached Bathroom', 'Individual Closets', 'Wi-Fi 5G', 'Laundry Service'],
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: false,
  },

  // FLOOR 2
  {
    roomNumber: '201',
    floor: 2,
    type: 'Executive Suite Single AC',
    isAc: true,
    price: 14500,
    capacity: 1,
    description: 'Corner studio with French windows, private coffee counter, premium wooden flooring, and ultra-fast 300 Mbps Wi-Fi.',
    facilities: ['Daikin Inverter AC', 'Mini Fridge', 'Smart TV with OTT', 'Attached Luxury Bath', 'King Single Bed', '24/7 Power Backup'],
    images: [
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: true,
  },
  {
    roomNumber: '202',
    floor: 2,
    type: 'Twin Sharing Premium AC',
    isAc: true,
    price: 9800,
    capacity: 2,
    description: 'Airy, beautifully decorated double room facing the peaceful garden courtyard.',
    facilities: ['Split AC', 'Garden View Balcony', 'Spacious Desks', 'Attached Bathroom', 'Individual RFID Lockers'],
    images: [
      'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1540518614846-7ede433c4ef2?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: false,
  },
  {
    roomNumber: '203',
    floor: 2,
    type: 'Twin Sharing Standard Non-AC',
    isAc: false,
    price: 7800,
    capacity: 2,
    description: 'Naturally cooled twin sharing room with personal study zones and serene blush decor.',
    facilities: ['Ceiling Fans', 'Attached Bath', 'Wardrobes', 'High-Speed Wi-Fi', 'Housekeeping'],
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1582582621959-48d27397dc69?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: false,
  },

  // FLOOR 3
  {
    roomNumber: '301',
    floor: 3,
    type: 'Skyline Deluxe Single AC',
    isAc: true,
    price: 14000,
    capacity: 1,
    description: 'Top-tier floor view with sunset vista, soundproof acoustic glass windows, and spacious study nook.',
    facilities: ['Split Inverter AC', 'Soundproof Windows', 'Attached Bath', 'Custom Study Desk', 'Book Shelves', 'Wi-Fi 6'],
    images: [
      'https://images.unsplash.com/photo-1582582621959-48d27397dc69?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: true,
  },
  {
    roomNumber: '302',
    floor: 3,
    type: 'Twin Sharing Luxury AC',
    isAc: true,
    price: 9500,
    capacity: 2,
    description: 'Chic dual occupancy room with twin beds, pastel interiors, and attached modern sanitary bathroom.',
    facilities: ['AC', 'Geyser', 'Attached Balcony', 'Individual Closets', 'Study Lamps'],
    images: [
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: false,
  },
  {
    roomNumber: '303',
    floor: 3,
    type: 'Triple Sharing Economy',
    isAc: false,
    price: 7000,
    capacity: 3,
    description: 'Vibrant three-resident room designed for collaborative student life with private storage bins.',
    facilities: ['Individual Desks', 'Attached Washroom', 'High-Speed Wi-Fi', 'Filtered Water Cooler on Floor'],
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: false,
  },

  // FLOOR 4
  {
    roomNumber: '401',
    floor: 4,
    type: 'Penthouse Terrace Single AC',
    isAc: true,
    price: 15500,
    capacity: 1,
    description: 'Exclusive 4th floor penthouse room with direct access to the rooftop sky garden and gazebo lounge.',
    facilities: ['Direct Terrace Access', 'Split AC', 'Smart Keyless Entry', 'Premium Mattress', 'Designer Study Setup', 'Ensuite Bath'],
    images: [
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: true,
  },
  {
    roomNumber: '402',
    floor: 4,
    type: 'Sky Terrace Twin AC',
    isAc: true,
    price: 10200,
    capacity: 2,
    description: 'Scenic twin room on the top floor with breezy open balcony, soft pink accent walls, and private study lamps.',
    facilities: ['Top Floor Breezy Balcony', 'Split AC', 'Attached Washroom', 'High-Speed Wi-Fi', 'Power Backup'],
    images: [
      'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1540518614846-7ede433c4ef2?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: false,
  },
  {
    roomNumber: '403',
    floor: 4,
    type: 'Quiet Study Twin AC',
    isAc: true,
    price: 9800,
    capacity: 2,
    description: 'Specially sound-isolated room located right next to the 4th floor reading library.',
    facilities: ['Sound Insulation', 'Dual Workstations', 'AC', 'High-Speed LAN Ports', 'Geyser'],
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80',
    ],
    availability: 'Available',
    featured: false,
  },
];

export const defaultFacilities = [
  {
    name: 'Hygienic 4-Meal Dining & Kitchen',
    category: 'Food & Nutrition',
    description: 'Freshly prepared breakfast, lunch, high tea, and dinner curated by expert chefs with vegetarian menu and RO water cooking.',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    icon: 'Utensils',
    order: 1,
    active: true,
  },
  {
    name: '24/7 Multi-Tier Security & Biometric',
    category: 'Safety',
    description: 'Round-the-clock female warden, full CCTV surveillance in common areas, and biometric smart-card entry system.',
    imageUrl: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
    icon: 'ShieldCheck',
    order: 2,
    active: true,
  },
  {
    name: 'Ultra High-Speed Campus Wi-Fi 6',
    category: 'Connectivity',
    description: 'Dual-band fiber optic internet with 300+ Mbps bandwidth across all 4 floors, dedicated to seamless study and project submissions.',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    icon: 'Wifi',
    order: 3,
    active: true,
  },
  {
    name: 'Climate Controlled AC Living',
    category: 'Comfort',
    description: 'Energy-efficient 5-star inverter ACs in rooms along with heavy-duty power backup generators for uninterrupted comfort in Jaipur summers.',
    imageUrl: 'https://images.unsplash.com/photo-1582582621959-48d27397dc69?auto=format&fit=crop&w=800&q=80',
    icon: 'Wind',
    order: 4,
    active: true,
  },
  {
    name: 'Quiet Study Lounges & Library',
    category: 'Academic',
    description: 'Dedicated air-conditioned study rooms with charging hubs, ergonomic chairs, and pin-drop silence for exam preparation.',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
    icon: 'BookOpen',
    order: 5,
    active: true,
  },
  {
    name: 'Daily Housekeeping & Free Laundry',
    category: 'Convenience',
    description: 'Daily room dusting and sanitization with automated washing machines and steam ironing spaces available on every floor.',
    imageUrl: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=800&q=80',
    icon: 'Sparkles',
    order: 6,
    active: true,
  },
  {
    name: 'RO Alkaline Water Dispensers',
    category: 'Health',
    description: 'Hot, cold, and ambient alkaline purified drinking water dispensers placed conveniently on all 4 floors.',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=800&q=80',
    icon: 'Droplets',
    order: 7,
    active: true,
  },
  {
    name: 'Rooftop Sky Terrace & Fitness Nook',
    category: 'Wellness',
    description: 'Scenic sunset open terrace with yoga mats, evening breeze gazebo, and indoor recreation games like table tennis.',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80',
    icon: 'HeartHandshake',
    order: 8,
    active: true,
  },
];

export const defaultTestimonials = [
  {
    name: 'Ananya Sharma',
    university: 'JECRC University • B.Tech AI & DS (3rd Year)',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-taking-notes-on-a-desk-41566-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    text: 'Living at Sree Kunj Girls PG for the past 2 years has made my college life so peaceful. It’s just 2 minutes walk to JECRC campus, and the food actually tastes like home cooked meals!',
    rating: 5,
    order: 1,
    active: true,
  },
  {
    name: 'Pooja Choudhary',
    university: 'Poornima University • MBA Marketing',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-student-girl-doing-her-homework-at-the-table-41571-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    text: 'The 24/7 security and biometric entry gave my parents complete peace of mind when I shifted from Delhi to Jaipur. The study lounges on the 4th floor are incredible.',
    rating: 5,
    order: 2,
    active: true,
  },
  {
    name: 'Riddhi Verma',
    university: 'JECRC University • B.Des Fashion',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-talking-on-video-call-with-her-laptop-42171-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
    text: 'Super clean rooms, instant power backup during summer, and ultra high speed Wi-Fi. It feels more like a boutique hotel than a standard PG!',
    rating: 5,
    order: 3,
    active: true,
  },
  {
    name: 'Sneha Meena',
    university: 'Poornima University • BCA 2nd Year',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-working-with-her-laptop-in-a-coffee-shop-41568-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    text: 'I booked my room through a video call tour while sitting at home in Udaipur. When I arrived, the room was exactly as shown. Highly recommended for girls!',
    rating: 5,
    order: 4,
    active: true,
  },
];
